[package]
name = "ghosty"
version = "0.3.6"
authors = ["John Teske <john.teske@protonmail.com>"]
description = "shared clipboard server/UI"
publish = false
edition = "2018"

[build-dependencies]
urlencoding = "1.1.1"

[dependencies]
bytes = "1.0.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
