[package]
name = "wlan-clip"
version = "0.1.0"
authors = ["John Teske <john.teske@protonmail.com>"]
description = "shared clipboard server/UI"
edition = "2018"

[dependencies]
futures = "0.3"
hyper = "0.13.1"
thruster = { version = "1.0.1", default_features = false, features=["hyper_server"] }
